const aliens=window.etAliens||[];
const $=selector=>document.querySelector(selector);
const storageKey='et-first-contact-save-v1';
function loadProgress(){try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');const valid=new Set(aliens.map(a=>a.id));return{done:Array.isArray(saved.done)?saved.done.filter(id=>valid.has(id)):[],score:Number(saved.score)||0,logs:Array.isArray(saved.logs)?saved.logs:[]}}catch{return{done:[],score:0,logs:[]}}}
const progress=loadProgress();
let currentAlien=null;
let soundEnabled=false;
function saveProgress(){try{localStorage.setItem(storageKey,JSON.stringify(progress))}catch{toast('Não foi possível salvar neste navegador.')}}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2200)}
function avatarPath(alien){return alien?.portrait||'assets/alien-01.png'}
function nextAlien(){return aliens.find(a=>!progress.done.includes(a.id))||null}
function openScreen(screen){document.querySelectorAll('.screen').forEach(node=>node.classList.remove('active'));$('#'+screen+'Screen').classList.add('active');document.querySelectorAll('.nav-item').forEach(node=>node.classList.remove('selected'));if(screen==='home')document.querySelector('[data-home].nav-item')?.classList.add('selected');if(screen==='collection')document.querySelector('[data-open-collection].nav-item')?.classList.add('selected');window.scrollTo({top:0,behavior:'smooth'})}
function updateProgress(){const n=progress.done.length;$('#progressLabel').textContent=`${n} / ${aliens.length} contatos`;$('#progressBar').style.width=`${aliens.length?Math.round(n/aliens.length*100):0}%`;$('#navProgress').textContent=n;$('#collectionCount').textContent=`${n} / ${aliens.length}`}
function missionFor(alien,index){
 const custom={
  zor:{title:'A frequência impossível',chapter:'SINAL 001 · NÉBULA-7',story:`No meio do ruído vindo de Nébula-7, uma voz surge em português. Zor se apresenta como ${alien.bio.charAt(0).toLowerCase()+alien.bio.slice(1)} A transmissão termina com uma pergunta: “Vocês conseguem nos ouvir?”`},
  luma:{title:'O jardim que responde',chapter:'SINAL 002 · ÓRBITA DE VÊNUS',story:'Uma sequência de imagens mostra flores acendendo uma a uma entre as nuvens. Luma envia uma mensagem: as plantas do planeta estão reagindo a um som que ela nunca ouviu.'},
  krix:{title:'Uma receita de Marte',chapter:'SINAL 003 · COLÔNIA AURORA',story:'Krix transmite uma receita ilustrada e pede ajuda para escolher um ingrediente terrestre. A cozinha da colônia está preparando um jantar para receber a primeira visita.'},
  siri:{title:'A canção sob o gelo',chapter:'SINAL 004 · CALISTO',story:'Uma melodia atravessa o gelo de Calisto. Sirius explica que as ondas do oceano subterrâneo formaram uma música nova e quer saber o que ela faz você sentir.'},
  pipa:{title:'O mapa das duas luas',chapter:'SINAL 005 · KEPLER-186F',story:'Pipa encontrou uma rota segura entre campos de flores luminosas e quer compartilhar o mapa. Antes, pergunta que lugar da Terra você colocaria no começo da jornada.'}
 };
 if(custom[alien.id])return custom[alien.id];
 return{title:`Uma mensagem de ${alien.planet}`,chapter:`SINAL ${String(index+1).padStart(3,'0')} · ${alien.planet.toUpperCase()}`,story:`${alien.name} acaba de entrar em contato. ${alien.bio} Na transmissão, mostra um pouco do seu mundo: ${alien.world}`};
}
function renderHome(){const alien=nextAlien(),complete=!alien;updateProgress();if(complete){$('#homeTitle').textContent='A galáxia respondeu';$('#homeSummary').textContent='Você registrou contato com todas as civilizações disponíveis.';$('#homePortrait').src='assets/alien-01.png';$('#homeNumber').textContent='✦';$('#startMission').innerHTML='Revisitar contatos <span>→</span>';$('#startMission').onclick=()=>openCollection();}else{const mission=missionFor(alien,progress.done.length);$('#homePortrait').src=avatarPath(alien);$('#homeTitle').textContent=mission.title;$('#homeSummary').textContent=`${alien.name} · ${alien.planet} — ${progress.done.length?'um novo sinal aguarda sua resposta':'alguém aguarda sua resposta'}.`;$('#homeNumber').textContent=String(progress.done.length+1).padStart(2,'0');$('#startMission').innerHTML=`${progress.done.length?'Continuar expedição':'Iniciar primeiro contato'} <span>→</span>`;$('#startMission').onclick=()=>startMission(alien);}
 const latest=progress.logs.at(-1);$('#recentLog').innerHTML=latest?`<span class="log-icon">✓</span><p><b>${escapeHtml(latest.title)}</b><br /><small>${escapeHtml(latest.summary)}</small></p><span class="log-arrow">↗</span>`:`<span class="log-icon">✧</span><p>Seu diário está vazio.<br /><small>A primeira missão espera por você.</small></p><span class="log-arrow">↗</span>`;
}
function startMission(alien){currentAlien=alien||nextAlien();if(!currentAlien){renderHome();return}const mission=missionFor(currentAlien,progress.done.length);$('#missionCount').textContent=`MISSÃO ${String(progress.done.length+1).padStart(2,'0')} DE ${aliens.length}`;$('#missionChapter').textContent=mission.chapter;$('#missionTitle').textContent=mission.title;$('#missionStory').textContent=mission.story;$('#missionPortrait').src=avatarPath(currentAlien);$('#missionPortrait').alt=`Retrato de ${currentAlien.name}`;$('#missionPlanet').textContent=currentAlien.planet.toUpperCase();$('#choiceArea').hidden=false;$('#outcome').hidden=true;renderChoices(currentAlien);openScreen('mission');}
function renderChoices(alien){const choices=[
 {label:'Respondo ao sinal e me apresento com calma.',kind:'greeting',score:2},
 {label:`Pergunto como é a vida em ${alien.planet}.`,kind:'curiosity',score:2},
 {label:'Observo mais um pouco antes de responder.',kind:'caution',score:1}
 ];$('#choices').innerHTML=choices.map((choice,index)=>`<button class="choice-button" data-choice="${index}"><span class="choice-index">0${index+1}</span><span>${escapeHtml(choice.label)}</span></button>`).join('');$('#choices').querySelectorAll('[data-choice]').forEach((button,index)=>button.onclick=()=>chooseResponse(alien,choices[index]));}
function chooseResponse(alien,choice){if(progress.done.includes(alien.id))return;const mission=missionFor(alien,progress.done.length);let response='';if(choice.kind==='greeting')response=`Você envia seu nome e confirma que recebeu a transmissão. ${alien.name} responde com alívio: “Que bom ouvir uma voz amiga.” ${alien.world}`;else if(choice.kind==='curiosity')response=`Você pergunta sobre a vida em ${alien.planet}. ${alien.name} compartilha: ${alien.world} ${alien.chatDetails?.climate||''}`;else response=`Você mantém distância e analisa o sinal. ${alien.name} entende sua cautela e envia uma mensagem mais clara: “Sem pressa. ${alien.hello}”`;
 progress.done.push(alien.id);progress.score+=choice.score;progress.logs.push({id:alien.id,title:mission.title,summary:`Primeiro contato com ${alien.name} · ${alien.planet}`,choice:choice.label});saveProgress();updateProgress();$('#choiceArea').hidden=true;$('#outcome').hidden=false;$('#outcomeText').textContent=response;$('#newContact').innerHTML=`<img src="${avatarPath(alien)}" alt="" /><div><strong>${escapeHtml(alien.name)} entrou no arquivo</strong><small>${escapeHtml(alien.planet)} · confiança +${choice.score}</small></div>`;const next=nextAlien();$('#continueMission').innerHTML=next?`Próximo sinal: ${escapeHtml(next.name)} <span>→</span>`:'Expedição concluída <span>✦</span>';$('#continueMission').onclick=()=>{renderHome();if(next)startMission(next);else openScreen('home')};renderCollection();}
function openCollection(){renderCollection();openScreen('collection')}
function renderCollection(){const unlocked=new Set(progress.done);$('#collectionGrid').innerHTML=aliens.map(alien=>{const known=unlocked.has(alien.id);return `<article class="collection-card ${known?'':'locked'}" data-id="${alien.id}" tabindex="0"><img loading="lazy" src="${avatarPath(alien)}" alt="" /><div class="card-overlay"></div><span class="lock-mark">${known?'✦':'⌑'}</span><div class="card-label"><strong>${known?escapeHtml(alien.name):'Sinal não decodificado'}</strong><small>${known?escapeHtml(alien.planet):'Complete uma missão para revelar'}</small></div></article>`}).join('');$('#collectionGrid').querySelectorAll('.collection-card').forEach(card=>{const open=()=>showContact(card.dataset.id);card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});}
function showContact(id){const alien=aliens.find(a=>a.id===id);if(!alien)return;if(!progress.done.includes(id)){toast('Complete uma missão para decodificar este sinal.');return}$('#modalPortrait').src=avatarPath(alien);$('#modalName').textContent=alien.name;$('#modalPlanet').textContent=`${alien.planet} · ${alien.distance}`;$('#modalBio').textContent=alien.bio;$('#modalWorld').textContent=alien.world;$('#contactModal').classList.add('open')}
function closeContact(){$('#contactModal').classList.remove('open')}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
document.querySelectorAll('[data-home]').forEach(button=>button.onclick=()=>{renderHome();openScreen('home')});document.querySelectorAll('[data-open-collection]').forEach(button=>button.onclick=openCollection);$('#startMission').onclick=()=>startMission(nextAlien());$('#closeContact').onclick=closeContact;$('#modalCloseAction').onclick=closeContact;$('#contactModal').onclick=e=>{if(e.target.id==='contactModal')closeContact()};$('#resetProgress').onclick=()=>{if(confirm('Apagar o progresso salvo neste navegador e começar de novo?')){progress.done=[];progress.score=0;progress.logs=[];saveProgress();renderHome();renderCollection();openScreen('home');toast('Expedição reiniciada.')}};$('#soundToggle').onclick=()=>{soundEnabled=!soundEnabled;$('#soundToggle').textContent=soundEnabled?'♫':'♩';$('#soundToggle').setAttribute('aria-label',soundEnabled?'Som ambiente ativado':'Som desligado');toast(soundEnabled?'Sinal sonoro ativado':'Sinal sonoro desligado')};
renderHome();renderCollection();updateProgress();
