const aliens=[
 {id:'zor',name:'Zor',age:128,pronouns:'ele/dele',planet:'Nébula-7',distance:'12 anos-luz',emoji:'👽',c1:'#30234b',c2:'#13142b',glow:'#ad76f5',orb1:'#cb82ff',orb2:'#4b3b9c',bio:'Coleciono estrelas cadentes e histórias que fazem rir. Procuro alguém para conhecer galáxias novas.',tags:['Humor cósmico','Música','Explorador'],world:'Em Nébula-7, chove cristais de gelo azul. A gente se reúne em cavernas quentinhas para contar histórias e ouvir o vento solar.',hello:'Oi, viajante! 🌠 Hoje o céu de Nébula-7 está cheio de auroras. Como foi seu dia por aí?'},
 {id:'luma',name:'Luma',age:96,pronouns:'ela/dela',planet:'Órbita de Vênus',distance:'18 anos-luz',emoji:'👩‍🚀',c1:'#48223f',c2:'#17152d',glow:'#ff8dba',orb1:'#ffb0c5',orb2:'#b04c9d',bio:'Botânica interplanetária. Faço jardins crescerem onde ninguém acredita que seja possível.',tags:['Natureza','Curiosa','Café de algas'],world:'Meu planeta tem jardins suspensos entre as nuvens. As flores brilham quando alguém conta uma lembrança feliz.',hello:'Olá! 🌷 Acabei de plantar uma semente que veio de um cometa. Qual lugar da Terra você acha mais bonito?'},
 {id:'krix',name:'Krix',age:204,pronouns:'elu/delu',planet:'Marte — colônia Aurora',distance:'22 anos-luz',emoji:'👾',c1:'#492c20',c2:'#211327',glow:'#ffb064',orb1:'#f89a61',orb2:'#9f4d44',bio:'Chef de cozinha marciana. Minha especialidade é inventar receitas com ingredientes improváveis.',tags:['Cozinha','Dança','Bom papo'],world:'Na colônia Aurora, construímos casas com paredes que armazenam o calor do dia. E sim: fazemos pizza com especiarias marcianas!',hello:'Ei! 🍕 Pergunta importante: você provaria uma pizza com queijo de meteorito? Prometo que é gostosa.'},
 {id:'siri',name:'Sirius',age:157,pronouns:'ele/dele',planet:'Calisto',distance:'31 anos-luz',emoji:'🛸',c1:'#1f3943',c2:'#11182d',glow:'#64d5d1',orb1:'#8dede2',orb2:'#3c7caa',bio:'Músico. Traduzo sons de luas distantes em canções para quem está com saudade.',tags:['Música','Gentil','Sonhador'],world:'Vivo perto de um oceano subterrâneo. À noite, dá para ouvir as ondas cantando por baixo do gelo.',hello:'Oi! 🎶 Hoje ouvi uma melodia linda nas ondas de Calisto. Que música você escuta quando quer relaxar?'},
 {id:'pipa',name:'Pipa',age:84,pronouns:'ela/dela',planet:'Kepler-186f',distance:'42 anos-luz',emoji:'👽',c1:'#35452c',c2:'#151d27',glow:'#b6e879',orb1:'#dbf69d',orb2:'#6ba37c',bio:'Pequena exploradora de grandes mundos. Tenho uma lista de coisas terrestres para experimentar!',tags:['Aventureira','Fotografia','Risos'],world:'Em Kepler-186f, existem duas luas verdes e campos de flores que mudam de cor com a música.',hello:'Olá, pessoa da Terra! 📸 Se eu visitar seu planeta, o que você me mostraria primeiro?'}
];
// A versão inicial já chega com 100 perfis: os cinco personagens principais
// acima e mais 95 combinações com identidade, planeta e história próprios.
const generatedNames=['Auri','Tavi','Nima','Vexo','Yara','Oru','Zeli','Mavi','Keno','Iria','Daro','Liri','Sumi','Ravi','Eko','Neri','Beli','Toma','Cira'];
const nameEnds=['','n','x','a','i'];
const worlds=[
 ['Auralis','um mundo de montanhas que brilham ao amanhecer','nascentes de luz morna'],['Thalassa','um planeta coberto por oceanos suspensos','cidades construídas em conchas gigantes'],['Vesper','um vale violeta sob três luas','jardins que florescem à noite'],['Orionis','uma ilha errante entre nuvens douradas','pontes de vento entre ilhas flutuantes'],['Myr','uma floresta antiga de árvores cristalinas','árvores que guardam as histórias da família'],['Eos','um deserto de areia azul e noites estreladas','mercados noturnos de especiarias cósmicas'],['Nix','um planeta gelado com mares sob o gelo','festas com lanternas coloridas no inverno'],['Caldera','um mundo de vulcões adormecidos e vales férteis','casas aquecidas pela energia das rochas'],['Lumen','uma cidade-planeta iluminada por algas','praças onde a música muda a cor das luzes'],['Aster','um arquipélago de luas pequenas','viagens de barco entre crateras'],['Pelago','um oceano profundo cheio de vida bioluminescente','corais que formam bairros inteiros'],['Solis','um planeta de campos dourados','piqueniques sob chuvas de meteoros'],['Umbra','uma floresta crepuscular tranquila','flores que abrem ao som de conversas'],['Cobalto','um mundo de cânions azuis','trens magnéticos que atravessam os cânions'],['Vega-4','um planeta de lagos rosados','corridas de veleiros movidos a vento solar'],['Prax','uma lua de cavernas habitáveis','murais que contam histórias de viajantes'],['Onda','um mundo onde o céu reflete o oceano','observatórios comunitários nas praias'],['Mirra','um planeta de jardins aromáticos','chá feito com ervas que só crescem ali'],['Koru','uma vasta planície sob auroras verdes','danças de boas-vindas em noites de aurora'],['Zênite','um planeta de cidades suspensas','bibliotecas públicas entre as nuvens']
];
const archetypes=[['cartógrafa de constelações','adora descobrir caminhos novos','Mapas','Aventura'],['médico de criaturas espaciais','cuida de todo ser que encontra','Cuidado','Ciência'],['artista de poeira estelar','pinta paisagens com pigmentos de cometa','Arte','Criatividade'],['professora de línguas cósmicas','coleciona palavras bonitas de cada planeta','Idiomas','Curiosidade'],['piloto de naves lentas','prefere viagens longas e boas conversas','Viagens','Calma'],['inventora de brinquedos','transforma peças antigas em pequenas maravilhas','Invenções','Diversão'],['chef de cozinha interplanetária','cria receitas para compartilhar com amigos','Culinária','Amizade'],['música de marés lunares','compõe canções inspiradas no espaço','Música','Sensibilidade'],['jardineiro de meteoros','faz nascer jardins nos lugares mais improváveis','Jardins','Natureza'],['fotógrafa de eclipses','espera o momento certo para cada imagem','Fotografia','Paciência']];
const generatedEmojis=['👽','👾','🛸','🪐','👻','🤖','🐙','🧑‍🚀','🌝','🧚','🦋','🐸'];
for(let i=0;i<95;i++){
 const p=generatedNames[Math.floor(i/5)], n=p+nameEnds[i%5]+(i>=50?String(Math.floor(i/50)+1):'');
 const w=worlds[i%worlds.length], ar=archetypes[Math.floor(i/archetypes.length)%archetypes.length];
 const pronouns=['ela/dela','ele/dele','elu/delu'][i%3];
 const emoji=generatedEmojis[i%generatedEmojis.length], age=72+((i*17)%240);
 const colorSets=[['#38264f','#17132b','#c389ff','#e2b2ff','#6245a2'],['#24434a','#151b30','#6cddd1','#acfff1','#397d92'],['#50313a','#21142e','#ff9bb7','#ffd0ad','#984c7a'],['#475035','#192131','#c1e580','#f4e8a2','#6c8752'],['#443b62','#171529','#ac9cff','#ffc9e7','#6954ab']][i%5];
 aliens.push({id:`alien-${i+6}`,name:n,age,pronouns,planet:w[0],distance:`${14+(i*7)%190} anos-luz`,emoji,c1:colorSets[0],c2:colorSets[1],glow:colorSets[2],orb1:colorSets[3],orb2:colorSets[4],bio:`${ar[0]} de ${w[0]}. ${ar[1]}. Quero conhecer alguém de outro mundo.`,tags:[ar[2],ar[3],['Bom papo','Explorador','Gentil','Sonhador','Bem-humorado'][i%5]],world:`Em ${w[0]}, ${w[1]}. No tempo livre, ${w[2]}.`,hello:`Oi, viajante! ✨ Sou ${n}, ${ar[0]} de ${w[0]}. O que você gostaria de saber sobre meu mundo?`});
}
const portraitsByPresentation={'ela/dela':[1,4,5,8,9],'ele/dele':[2,3,6,7,10],'elu/delu':[3,5,6,9,10]};
const portraitCounters={'ela/dela':0,'ele/dele':0,'elu/delu':0};
aliens.forEach(a=>{const pool=portraitsByPresentation[a.pronouns]||[1,2,3,4,5,6,7,8,9,10],key=a.pronouns||'all',idx=portraitCounters[key]||0;a.portrait=`assets/alien-${String(pool[idx%pool.length]).padStart(2,'0')}.png`;portraitCounters[key]=idx+1});
const chatDetails=[
 {job:'explorador de rotas estelares',food:'frutas de casca azul e chá de cristais',climate:'frio e seco, com auroras frequentes',culture:'costumamos reunir amigos para contar histórias ao anoitecer'},
 {job:'botânica de jardins suspensos',food:'algas doces e flores comestíveis',climate:'ameno nas cidades e úmido perto dos jardins',culture:'celebramos cada estação plantando algo em comunidade'},
 {job:'chef da colônia Aurora',food:'raízes assadas com especiarias marcianas',climate:'seco durante o dia e bem frio à noite',culture:'compartilhar uma refeição é nosso jeito favorito de receber visitas'},
 {job:'músico das marés de Calisto',food:'sopa de algas e frutos do oceano subterrâneo',climate:'gelado na superfície, mas confortável nas cidades sob o gelo',culture:'a música acompanha os encontros e as celebrações'},
 {job:'fotógrafa de paisagens',food:'frutas leves e pães de sementes locais',climate:'temperado, com duas luas visíveis à noite',culture:'gostamos de explorar a natureza e registrar momentos juntos'},
 {job:'cartógrafa de constelações',food:'pães de sementes e infusões aromáticas',climate:'varia bastante entre as regiões do planeta',culture:'trocamos mapas e relatos de viagem quando nos encontramos'},
 {job:'pesquisador de ecossistemas',food:'pratos vegetais preparados com ingredientes locais',climate:'suave, com longas noites estreladas',culture:'a curiosidade e a troca de conhecimento fazem parte do cotidiano'},
 {job:'artista de paisagens cósmicas',food:'frutas luminosas e caldos quentes',climate:'fresco, com mudanças de cor no céu',culture:'música e arte são formas comuns de contar nossa história'},
 {job:'piloto de naves de pesquisa',food:'tubérculos assados e chá de ervas',climate:'frio nas regiões altas e ameno nos vales',culture:'recebemos viajantes com uma refeição e muitas perguntas'},
 {job:'cuidador de jardins comunitários',food:'vegetais crocantes e frutas de estação',climate:'agradável, com chuvas curtas ao entardecer',culture:'muitas decisões são tomadas em encontros abertos da comunidade'}
];
const rolesById={zor:'explorador de galáxias e contador de histórias',luma:'botânica interplanetária',krix:'chef da colônia Aurora',siri:'músico das marés de Calisto',pipa:'exploradora e fotógrafa'};
aliens.forEach((a,i)=>{const detail=chatDetails[i%chatDetails.length];a.chatDetails={...detail,...a.chatDetails};a.chatDetails.job=rolesById[a.id]||a.bio.split('.')[0]});
function loadSavedState(){try{const saved=JSON.parse(localStorage.getItem('et-free-prototype')||'{}');return{index:Number.isInteger(saved.index)?Math.max(0,Math.min(saved.index,aliens.length-1)):0,liked:Array.isArray(saved.liked)?saved.liked.filter(id=>aliens.some(a=>a.id===id)):[],messages:saved.messages&&typeof saved.messages==='object'?saved.messages:{},history:Array.isArray(saved.history)?saved.history:[],userNames:saved.userNames&&typeof saved.userNames==='object'?saved.userNames:{}}}catch{return{index:0,liked:[],messages:{},history:[],userNames:{}}}}
const state={...loadSavedState(),current:null};
function saveState(){try{localStorage.setItem('et-free-prototype',JSON.stringify({index:state.index,liked:state.liked,messages:state.messages,history:state.history,userNames:state.userNames}))}catch{toast('Não foi possível salvar neste navegador')}}
const $=s=>document.querySelector(s);const deck=$('#deck');
function avatarVars(a){return `style="--glow:${a.glow};--c1:${a.c1};--c2:${a.c2};--orb1:${a.orb1};--orb2:${a.orb2}"`}
function renderCard(){if(state.index>=aliens.length){deck.innerHTML=`<div class="profile-card profile-art" style="--glow:#7d60cb;--c1:#282045;--c2:#131329;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:35px;text-align:center"><div style="font-size:58px">✧</div><h2 style="font:600 22px 'Space Grotesk'">Você explorou tudo por enquanto</h2><p style="font-size:12px;color:#c7bfd4">Novos sinais podem chegar a qualquer momento.</p><button class="primary" id="restart">Rever perfis</button></div>`;$('#restart').onclick=()=>{state.index=0;renderCard()};return}const a=aliens[state.index];deck.innerHTML=`<article class="profile-card" ${avatarVars(a)}><div class="profile-art" ${avatarVars(a)}><img class="profile-photo" src="${a.portrait}" alt="Retrato de ${a.name}" /><div class="art-label">✦ SINAL DE ${a.planet.toUpperCase()}</div></div><div class="card-shade"></div><div class="card-info"><div class="online">Transmissão ativa</div><div class="name-line"><h2>${a.name}</h2><span class="age">${a.age}</span></div><div class="planet-tag">⌖ ${a.planet} &nbsp;·&nbsp; ${a.distance}</div><p class="bio">${a.bio}</p><div class="tags">${a.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div></article>`;const card=deck.firstElementChild;let startX=0;card.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true});card.addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-startX;if(Math.abs(dx)>70)advance(dx>0)},{passive:true});card.addEventListener('click',e=>{if(!e.target.closest('button'))toast(`${a.name} • ${a.pronouns} • ${a.planet}`)})}
function advance(liked){if(state.index>=aliens.length)return;const a=aliens[state.index];state.history.push(state.index);state.index++;if(liked){if(!state.liked.includes(a.id))state.liked.push(a.id);if(!state.messages[a.id])state.messages[a.id]=[{from:'them',text:a.hello}];renderCounts();showMatch(a)}saveState();renderCard()}
function showMatch(a){$('#matchAvatar').textContent='';$('#matchAvatar').setAttribute('style',`${avatarVars(a)};background-image:url('${a.portrait}')`);$('#matchText').textContent=`Você e ${a.name} começaram a se seguir pelo universo. Que tal mandar uma mensagem?`;$('#matchModal').classList.add('open');$('#startChat').onclick=()=>{closeModal();openConversation(a.id)};$('#keepExploring').onclick=closeModal;$('#closeModal').onclick=closeModal}
function closeModal(){$('#matchModal').classList.remove('open')}
function renderCounts(){$('#chatCount').textContent=state.liked.length;$('#navCount').textContent=state.liked.length;$('#chatCount').style.display=state.liked.length?'block':'none';$('#navCount').style.display=state.liked.length?'block':'none';renderChats()}
function renderChats(){const list=$('#chatList');list.innerHTML=state.liked.map(id=>{const a=aliens.find(x=>x.id===id),last=state.messages[id]?.at(-1)?.text||'Conexão estabelecida';return `<div class="chat-row" data-id="${id}" ${avatarVars(a)}><div class="mini-avatar" ${avatarVars(a)} style="background-image:url('${a.portrait}')"></div><div class="chat-meta"><strong>${a.name}</strong><small>${last}</small></div><time>agora</time></div>`}).join('');$('#emptyChats').style.display=state.liked.length?'none':'block';list.querySelectorAll('.chat-row').forEach(row=>row.onclick=()=>openConversation(row.dataset.id))}
function showScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('#'+name).classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('selected'));if(name==='discover')document.querySelector('[data-discover].nav-item')?.classList.add('selected');if(name==='chats')document.querySelector('[data-chats].nav-item')?.classList.add('selected')}
function openConversation(id){const a=aliens.find(x=>x.id===id);if(!a)return;state.current=id;$('#chatAvatar').textContent='';$('#chatAvatar').setAttribute('style',`${avatarVars(a)};background-image:url('${a.portrait}')`);$('#chatName').textContent=a.name;$('#chatPlanet').textContent=`${a.pronouns} · ${a.planet}`;$('#chatWorld').innerHTML=`✦ <b>Diário de ${a.name}:</b> ${a.world}<small class="free-mode-note">Modo offline · respostas baseadas na história do perfil</small>`;renderQuickPrompts(a);showScreen('conversation');renderMessages()}
function renderQuickPrompts(a){const suggestions=[`Como é viver em ${a.planet}?`,'O que você costuma comer?','O que gosta de fazer no tempo livre?','Me conta uma tradição daí.'];const box=$('#quickPrompts');box.innerHTML=suggestions.map(q=>`<button class="quick-prompt" type="button">${escapeHtml(q)}</button>`).join('');box.querySelectorAll('.quick-prompt').forEach((button,i)=>button.onclick=()=>{const input=$('#messageInput');input.value=suggestions[i];$('#messageForm').requestSubmit()})}
function renderMessages(conversationId=state.current){const box=$('#messages');if(!conversationId||conversationId!==state.current)return;box.innerHTML=(state.messages[conversationId]||[]).map(m=>`<div class="bubble ${m.from}">${escapeHtml(m.text)}<time>${m.from==='me'?'agora':'transmissão recebida'}</time></div>`).join('');box.scrollTop=box.scrollHeight}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function replyFor(a,msg){
 const raw=msg.trim(),m=raw.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim(),d=a.chatDetails;
 const has=(...terms)=>terms.some(term=>m.includes(term));
 const intro=raw.match(/(?:me chamo|meu nome e|sou o|sou a)\s+([\p{L}]+)/iu);
 if(intro){state.userNames[a.id]=intro[1];saveState();return `Prazer em te conhecer, ${state.userNames[a.id]}! Eu sou ${a.name}, de ${a.planet}. O que você mais gosta de fazer no seu planeta?`}
 if(has('lembra meu nome','qual meu nome','como eu me chamo'))return state.userNames[a.id]?`Claro, ${state.userNames[a.id]}! Lembro que você me contou seu nome. Quer continuar falando sobre ${a.planet}?`:'Ainda não sei seu nome. Se quiser, pode me dizer: “me chamo…”.';
 if(has('qual seu nome','como voce se chama','quem e voce','seu nome'))return `Eu sou ${a.name}. Venho de ${a.planet} e trabalho como ${d.job}. E você, como gosta de ser chamado?`;
 if(has('planeta','mundo','mora','moradia','vive','reside','casa','lar','origem','de onde'))return `Eu moro em ${a.planet}. ${a.world} ${d.climate}.`;
 if(has('vida ai','vida no','como e viver','como e a vida','dia a dia','rotina'))return `A vida em ${a.planet} é assim: ${a.world} ${d.climate}. No meu dia a dia, trabalho como ${d.job}; também gosto de ${a.tags[0].toLowerCase()}.`;
 if(has('trabalho','profissao','profissão','ocupacao','ocupação','faz da vida','trabalha com','o que voce faz'))return `Trabalho como ${d.job}. ${a.bio} O que você faz por aí?`;
 if(has('comida','comer','come','prato','alimentacao','alimentação','favorita','favorito','cozinha'))return `Por aqui, gosto de ${d.food}. A culinária de ${a.planet} usa ingredientes bem diferentes dos da Terra. Qual é sua comida favorita?`;
 if(has('clima','temperatura','tempo faz','frio','calor','chove','chuva','estacao','estação'))return `O clima em ${a.planet} é ${d.climate}. ${a.world}`;
 if(has('costume','cultura','tradicao','tradição','celebr','povo','habitantes'))return `Uma tradição de ${a.planet}: ${d.culture}. E como são os costumes onde você vive?`;
 if(has('hobby','tempo livre','passatempo','gosta de fazer','o que gosta','curte fazer'))return `No tempo livre, gosto de ${a.tags.map(t=>t.toLowerCase()).join(' e ')}. ${d.culture}. E você?`;
 if(has('terra','terrestre','humanos','humanidade','seu planeta'))return `A Terra me parece fascinante. Ainda estou aprendendo sobre a vida humana. O que você acha que eu deveria conhecer primeiro?`;
 if(has('visitar','visita','conhecer a terra','ir para a terra','viajar'))return `Eu adoraria conhecer a Terra algum dia. Gosto de viajar e aprender com outros mundos. Qual lugar você me mostraria primeiro?`;
 if(has('relacionamento','namoro','encontro','procura','busca','conexao','conexão','romance'))return `Estou aqui para conhecer alguém com quem a conversa flua e descobrir novos mundos juntos. O que você procura numa conexão?`;
 if(has('idade','quantos anos'))return `Tenho ${a.age} ciclos de vida. A contagem do tempo em ${a.planet} é um pouco diferente da terrestre!`;
 if(has('oi','ola','olá','bom dia','boa tarde','boa noite','tudo bem','como vai'))return `Oi! Que bom conversar com você. ${a.hello}`;
 return `Não tenho uma resposta boa para isso ainda — pode me perguntar sobre meu planeta, meu trabalho, a comida ou como é a vida por aqui?`;
}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#pass').onclick=()=>advance(false);$('#like').onclick=()=>advance(true);$('#rewind').onclick=()=>{if(state.history.length){state.index=state.history.pop();saveState();renderCard()}else toast('Ainda não há perfil anterior')};$('#openChats').onclick=()=>showScreen('chats');document.querySelectorAll('[data-chats]').forEach(x=>x.onclick=()=>showScreen('chats'));document.querySelectorAll('[data-discover]').forEach(x=>x.onclick=()=>showScreen('discover'));document.querySelectorAll('[data-back]').forEach(x=>x.onclick=()=>showScreen('discover'));$('#backChats').onclick=()=>showScreen('chats');$('#filterButton').onclick=()=>toast('Mais filtros chegam em breve ✦');$('#profileTab').onclick=()=>toast('Seu perfil terrestre chega em breve ✦');
$('#messageForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#messageInput'),text=input.value.trim();if(!text||!state.current)return;const id=state.current,a=aliens.find(x=>x.id===id);if(!state.messages[id])state.messages[id]=[];state.messages[id].push({from:'me',text});input.value='';saveState();renderMessages(id);setTimeout(()=>{state.messages[id].push({from:'them',text:replyFor(a,text)});saveState();if(state.current===id)renderMessages(id);renderChats()},350);renderChats()});renderCard();renderCounts();
