const aliens=[
 {id:'zor',name:'Zor',age:128,pronouns:'ele/dele',planet:'Nébula-7',distance:'12 anos-luz',emoji:'👽',c1:'#30234b',c2:'#13142b',glow:'#ad76f5',orb1:'#cb82ff',orb2:'#4b3b9c',bio:'Coleciono estrelas cadentes e histórias que fazem rir. Procuro alguém para conhecer galáxias novas.',tags:['Humor cósmico','Música','Explorador'],world:'Em Nébula-7, chove cristais de gelo azul. A gente se reúne em cavernas quentinhas para contar histórias e ouvir o vento solar.',hello:'Oi, viajante! 🌠 Hoje o céu de Nébula-7 está cheio de auroras. Como foi seu dia por aí?'},
 {id:'luma',name:'Luma',age:96,pronouns:'ela/dela',planet:'Órbita de Vênus',distance:'18 anos-luz',emoji:'👩‍🚀',c1:'#48223f',c2:'#17152d',glow:'#ff8dba',orb1:'#ffb0c5',orb2:'#b04c9d',bio:'Botânica interplanetária. Faço jardins crescerem onde ninguém acredita que seja possível.',tags:['Natureza','Curiosa','Café de algas'],world:'Meu planeta tem jardins suspensos entre as nuvens. As flores brilham quando alguém conta uma lembrança feliz.',hello:'Olá! 🌷 Acabei de plantar uma semente que veio de um cometa. Qual lugar da Terra você acha mais bonito?'},
 {id:'krix',name:'Krix',age:204,pronouns:'elu/delu',planet:'Marte — colônia Aurora',distance:'22 anos-luz',emoji:'👾',c1:'#492c20',c2:'#211327',glow:'#ffb064',orb1:'#f89a61',orb2:'#9f4d44',bio:'Chef de cozinha marciana. Minha especialidade é inventar receitas com ingredientes improváveis.',tags:['Cozinha','Dança','Bom papo'],world:'Na colônia Aurora, construímos casas com paredes que armazenam o calor do dia. E sim: fazemos pizza com especiarias marcianas!',hello:'Ei! 🍕 Pergunta importante: você provaria uma pizza com queijo de meteorito? Prometo que é gostosa.'},
 {id:'siri',name:'Sirius',age:157,pronouns:'ele/dele',planet:'Calisto',distance:'31 anos-luz',emoji:'🛸',c1:'#1f3943',c2:'#11182d',glow:'#64d5d1',orb1:'#8dede2',orb2:'#3c7caa',bio:'Músico. Traduzo sons de luas distantes em canções para quem está com saudade.',tags:['Música','Gentil','Sonhador'],world:'Vivo perto de um oceano subterrâneo. À noite, dá para ouvir as ondas cantando por baixo do gelo.',hello:'Oi! 🎶 Hoje ouvi uma melodia linda nas ondas de Calisto. Que música você escuta quando quer relaxar?'},
 {id:'pipa',name:'Pipa',age:84,pronouns:'ela/dela',planet:'Kepler-186f',distance:'42 anos-luz',emoji:'👽',c1:'#35452c',c2:'#151d27',glow:'#b6e879',orb1:'#dbf69d',orb2:'#6ba37c',bio:'Pequena exploradora de grandes mundos. Tenho uma lista de coisas terrestres para experimentar!',tags:['Aventureira','Fotografia','Risos'],world:'Em Kepler-186f, existem duas luas verdes e campos de flores que mudam de cor com a música.',hello:'Olá, pessoa da Terra! 📸 Se eu visitar seu planeta, o que você me mostraria primeiro?'}
];
// A versão inicial já chega com 100 perfis: os cinco personagens principais
// acima e mais 95 combinações com identidade, planeta e história próprios.
const generatedNames=['Auri','Tavi','Nima','Vexo','Yara','Oru','Zeli','Mavi','Keno','Iria','Daro','Liri','Sumi','Ravi','Eko','Neri','Beli','Toma','Cira'];
const nameEnds=['','n','x','a','i'];
const worlds=[
 ['Auralis','um mundo de montanhas que brilham ao amanhecer','nascentes de luz morna'],['Thalassa','um planeta coberto por oceanos suspensos','cidades construídas em conchas gigantes'],['Vesper','um vale violeta sob três luas','jardins que florescem à noite'],['Orionis','uma ilha errante entre nuvens douradas','pontes de vento entre ilhas flutuantes'],['Myr','uma floresta antiga de árvores cristalinas','árvores que guardam as histórias da família'],['Eos','um deserto de areia azul e noites estreladas','mercados noturnos de especiarias cósmicas'],['Nix','um planeta gelado com mares sob o gelo','festas com lanternas coloridas no inverno'],['Caldera','um mundo de vulcões adormecidos e vales férteis','casas aquecidas pela energia das rochas'],['Lumen','uma cidade-planeta iluminada por algas','praças onde a música muda a cor das luzes'],['Aster','um arquipélago de luas pequenas','viagens de barco entre crateras'],['Pelago','um oceano profundo cheio de vida bioluminescente','corais que formam bairros inteiros'],['Solis','um planeta de campos dourados','piqueniques sob chuvas de meteoros'],['Umbra','uma floresta crepuscular tranquila','flores que abrem ao som de conversas'],['Cobalto','um mundo de cânions azuis','trens magnéticos que atravessam os cânions'],['Vega-4','um planeta de lagos rosados','corridas de veleiros movidos a vento solar'],['Prax','uma lua de cavernas habitáveis','murais que contam histórias de viajantes'],['Onda','um mundo onde o céu reflete o oceano','observatórios comunitários nas praias'],['Mirra','um planeta de jardins aromáticos','chá feito com ervas que só crescem ali'],['Koru','uma vasta planície sob auroras verdes','danças de boas-vindas em noites de aurora'],['Zênite','um planeta de cidades suspensas','bibliotecas públicas entre as nuvens']
];
const archetypes=[['cartógrafa de constelações','adora descobrir caminhos novos','Mapas','Aventura'],['médico de criaturas espaciais','cuida de todo ser que encontra','Cuidado','Ciência'],['artista de poeira estelar','pinta paisagens com pigmentos de cometa','Arte','Criatividade'],['professora de línguas cósmicas','coleciona palavras bonitas de cada planeta','Idiomas','Curiosidade'],['piloto de naves lentas','prefere viagens longas e boas conversas','Viagens','Calma'],['inventora de brinquedos','transforma peças antigas em pequenas maravilhas','Invenções','Diversão'],['chef de cozinha interplanetária','cria receitas para compartilhar com amigos','Culinária','Amizade'],['música de marés lunares','compõe canções inspiradas no espaço','Música','Sensibilidade'],['jardineiro de meteoros','faz nascer jardins nos lugares mais improváveis','Jardins','Natureza'],['fotógrafa de eclipses','espera o momento certo para cada imagem','Fotografia','Paciência']];
const generatedEmojis=['👽','👾','🛸','🪐','👻','🤖','🐙','🧑‍🚀','🌝','🧚','🦋','🐸'];
for(let i=0;i<95;i++){
 const p=generatedNames[Math.floor(i/5)], n=p+nameEnds[i%5]+(i>=50?String(Math.floor(i/50)+1):'');
 const w=worlds[i%worlds.length], ar=archetypes[Math.floor(i/archetypes.length)%archetypes.length];
 const pronouns=['ela/dela','ele/dele','elu/delu'][i%3];
 const emoji=generatedEmojis[i%generatedEmojis.length], age=72+((i*17)%240);
 const colorSets=[['#38264f','#17132b','#c389ff','#e2b2ff','#6245a2'],['#24434a','#151b30','#6cddd1','#acfff1','#397d92'],['#50313a','#21142e','#ff9bb7','#ffd0ad','#984c7a'],['#475035','#192131','#c1e580','#f4e8a2','#6c8752'],['#443b62','#171529','#ac9cff','#ffc9e7','#6954ab']][i%5];
 aliens.push({id:`alien-${i+6}`,name:n,age,pronouns,planet:w[0],distance:`${14+(i*7)%190} anos-luz`,emoji,c1:colorSets[0],c2:colorSets[1],glow:colorSets[2],orb1:colorSets[3],orb2:colorSets[4],bio:`${ar[0]} de ${w[0]}. ${ar[1]}. Quero conhecer alguém de outro mundo.`,tags:[ar[2],ar[3],['Bom papo','Explorador','Gentil','Sonhador','Bem-humorado'][i%5]],world:`Em ${w[0]}, ${w[1]}. No tempo livre, ${w[2]}.`,hello:`Oi, viajante! ✨ Sou ${n}, ${ar[0]} de ${w[0]}. O que você gostaria de saber sobre meu mundo?`});
}
const portraitsByPresentation={'ela/dela':[1,4,5,8,9],'ele/dele':[2,3,6,7,10],'elu/delu':[3,5,6,9,10]};
const portraitCounters={'ela/dela':0,'ele/dele':0,'elu/delu':0};
aliens.forEach(a=>{const pool=portraitsByPresentation[a.pronouns]||[1,2,3,4,5,6,7,8,9,10],key=a.pronouns||'all',idx=portraitCounters[key]||0;a.portrait=`assets/alien-${String(pool[idx%pool.length]).padStart(2,'0')}.png`;portraitCounters[key]=idx+1});
const chatDetails=[
 {job:'explorador de rotas estelares',food:'frutas de casca azul e chá de cristais',climate:'frio e seco, com auroras frequentes',culture:'costumamos reunir amigos para contar histórias ao anoitecer'},
 {job:'botânica de jardins suspensos',food:'algas doces e flores comestíveis',climate:'ameno nas cidades e úmido perto dos jardins',culture:'celebramos cada estação plantando algo em comunidade'},
 {job:'chef da colônia Aurora',food:'raízes assadas com especiarias marcianas',climate:'seco durante o dia e bem frio à noite',culture:'compartilhar uma refeição é nosso jeito favorito de receber visitas'},
 {job:'músico das marés de Calisto',food:'sopa de algas e frutos do oceano subterrâneo',climate:'gelado na superfície, mas confortável nas cidades sob o gelo',culture:'a música acompanha os encontros e as celebrações'},
 {job:'fotógrafa de paisagens',food:'frutas leves e pães de sementes locais',climate:'temperado, com duas luas visíveis à noite',culture:'gostamos de explorar a natureza e registrar momentos juntos'},
 {job:'cartógrafa de constelações',food:'pães de sementes e infusões aromáticas',climate:'varia bastante entre as regiões do planeta',culture:'trocamos mapas e relatos de viagem quando nos encontramos'},
 {job:'pesquisador de ecossistemas',food:'pratos vegetais preparados com ingredientes locais',climate:'suave, com longas noites estreladas',culture:'a curiosidade e a troca de conhecimento fazem parte do cotidiano'},
 {job:'artista de paisagens cósmicas',food:'frutas luminosas e caldos quentes',climate:'fresco, com mudanças de cor no céu',culture:'música e arte são formas comuns de contar nossa história'},
 {job:'piloto de naves de pesquisa',food:'tubérculos assados e chá de ervas',climate:'frio nas regiões altas e ameno nos vales',culture:'recebemos viajantes com uma refeição e muitas perguntas'},
 {job:'cuidador de jardins comunitários',food:'vegetais crocantes e frutas de estação',climate:'agradável, com chuvas curtas ao entardecer',culture:'muitas decisões são tomadas em encontros abertos da comunidade'}
];
const rolesById={zor:'explorador de galáxias e contador de histórias',luma:'botânica interplanetária',krix:'chef da colônia Aurora',siri:'músico das marés de Calisto',pipa:'exploradora e fotógrafa'};
aliens.forEach((a,i)=>{const detail=chatDetails[i%chatDetails.length];a.chatDetails={...detail,...a.chatDetails};a.chatDetails.job=rolesById[a.id]||a.bio.split('.')[0]});
function loadSavedState(){try{const saved=JSON.parse(localStorage.getItem('et-free-prototype')||'{}');return{index:Number.isInteger(saved.index)?Math.max(0,Math.min(saved.index,aliens.length-1)):0,liked:Array.isArray(saved.liked)?saved.liked.filter(id=>aliens.some(a=>a.id===id)):[],messages:saved.messages&&typeof saved.messages==='object'?saved.messages:{},history:Array.isArray(saved.history)?saved.history:[],userNames:saved.userNames&&typeof saved.userNames==='object'?saved.userNames:{}}}catch{return{index:0,liked:[],messages:{},history:[],userNames:{}}}}
window.etAliens=aliens;
